### ISSUE TITLE
Add Conditional Rendering

### ISSUE THREAD

**Issue by AngeloFilaseta** [AngeloFilaseta/vocabolangelo-rdf#6]
It would be cool if some sections only renders if content is available, for example:

 Parole correlate: 
 - Word 1
 - Word 2

is okay

Parole correlate:

isn't.

This should be a thing in every section not only in "Parole correlate"

**Comment by j3yxz** [comment]
Working on this for "person.html" rn

**Comment by AngeloFilaseta** [comment]
It should be possibile to link a pull request to the issue, I'll check in a bit

**Comment by AngeloFilaseta** [comment]
Resolved in #8
